// Generated by scripts/build-icons.mjs. Do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

export type Jersey = {
  id: string;
  name: string;
  preview: ImageSourcePropType;
  /** Jersey without number, for player avatars. */
  blank: ImageSourcePropType;
  /** Colour of the printing (name, number) on this jersey. */
  ink: string;
};

/** The first jersey is the default app icon. */
export const JERSEYS: Jersey[] = [
  { id: 'IndigoOrange', name: 'Indigo, bande orange', preview: require('../../assets/icons/IndigoOrange/preview.png'), blank: require('../../assets/icons/IndigoOrange/blank.png'), ink: '#fff' },
  { id: 'WhiteSky', name: 'Blanc et ciel', preview: require('../../assets/icons/WhiteSky/preview.png'), blank: require('../../assets/icons/WhiteSky/blank.png'), ink: '#1B2A4A' },
  { id: 'RedBlackStripes', name: 'Rayé rouge et noir', preview: require('../../assets/icons/RedBlackStripes/preview.png'), blank: require('../../assets/icons/RedBlackStripes/blank.png'), ink: '#fff' },
  { id: 'BlackWhiteStripes', name: 'Rayé noir et blanc', preview: require('../../assets/icons/BlackWhiteStripes/preview.png'), blank: require('../../assets/icons/BlackWhiteStripes/blank.png'), ink: '#D4A017' },
  { id: 'BlueBlackStripes', name: 'Rayé bleu et noir', preview: require('../../assets/icons/BlueBlackStripes/preview.png'), blank: require('../../assets/icons/BlueBlackStripes/blank.png'), ink: '#fff' },
  { id: 'GarnetBlueStripes', name: 'Rayé grenat et bleu', preview: require('../../assets/icons/GarnetBlueStripes/preview.png'), blank: require('../../assets/icons/GarnetBlueStripes/blank.png'), ink: '#FFD23F' },
  { id: 'AllRed', name: 'Rouge intégral', preview: require('../../assets/icons/AllRed/preview.png'), blank: require('../../assets/icons/AllRed/blank.png'), ink: '#fff' },
  { id: 'RedWhiteCollar', name: 'Rouge, col blanc', preview: require('../../assets/icons/RedWhiteCollar/preview.png'), blank: require('../../assets/icons/RedWhiteCollar/blank.png'), ink: '#fff' },
  { id: 'SkyNavy', name: 'Bleu ciel, col marine', preview: require('../../assets/icons/SkyNavy/preview.png'), blank: require('../../assets/icons/SkyNavy/blank.png'), ink: '#1C2C5B' },
  { id: 'AllWhiteGold', name: 'Tout blanc, filet or', preview: require('../../assets/icons/AllWhiteGold/preview.png'), blank: require('../../assets/icons/AllWhiteGold/blank.png'), ink: '#C9A227' },
  { id: 'RedWhiteSleeves', name: 'Rouge, manches blanches', preview: require('../../assets/icons/RedWhiteSleeves/preview.png'), blank: require('../../assets/icons/RedWhiteSleeves/blank.png'), ink: '#fff' },
  { id: 'RedWhiteSides', name: 'Rouge, flancs blancs', preview: require('../../assets/icons/RedWhiteSides/preview.png'), blank: require('../../assets/icons/RedWhiteSides/blank.png'), ink: '#fff' },
  { id: 'YellowBlack', name: 'Jaune et noir', preview: require('../../assets/icons/YellowBlack/preview.png'), blank: require('../../assets/icons/YellowBlack/blank.png'), ink: '#111111' },
  { id: 'GoldRed', name: 'Or et rouge', preview: require('../../assets/icons/GoldRed/preview.png'), blank: require('../../assets/icons/GoldRed/blank.png'), ink: '#D7192A' },
  { id: 'RedWhiteSplit', name: 'Coupé rouge et blanc', preview: require('../../assets/icons/RedWhiteSplit/preview.png'), blank: require('../../assets/icons/RedWhiteSplit/blank.png'), ink: '#111111' },
  { id: 'ForestGreen', name: 'Vert forêt', preview: require('../../assets/icons/ForestGreen/preview.png'), blank: require('../../assets/icons/ForestGreen/blank.png'), ink: '#fff' },
  { id: 'WhiteChevron', name: 'Blanc, chevron bicolore', preview: require('../../assets/icons/WhiteChevron/preview.png'), blank: require('../../assets/icons/WhiteChevron/blank.png'), ink: '#1B2A4A' },
];
