// Generated by scripts/build-icons.mjs. Do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

export type Jersey = { id: string; name: string; preview: ImageSourcePropType };

/** The first jersey is the default app icon. */
export const JERSEYS: Jersey[] = [
  { id: 'IndigoOrange', name: 'Indigo, bande orange', preview: require('../../assets/icons/IndigoOrange/preview.png') },
  { id: 'WhiteSky', name: 'Blanc et ciel', preview: require('../../assets/icons/WhiteSky/preview.png') },
  { id: 'RedBlackStripes', name: 'Rayé rouge et noir', preview: require('../../assets/icons/RedBlackStripes/preview.png') },
  { id: 'BlackWhiteStripes', name: 'Rayé noir et blanc', preview: require('../../assets/icons/BlackWhiteStripes/preview.png') },
  { id: 'BlueBlackStripes', name: 'Rayé bleu et noir', preview: require('../../assets/icons/BlueBlackStripes/preview.png') },
  { id: 'GarnetBlueStripes', name: 'Rayé grenat et bleu', preview: require('../../assets/icons/GarnetBlueStripes/preview.png') },
  { id: 'AllRed', name: 'Rouge intégral', preview: require('../../assets/icons/AllRed/preview.png') },
  { id: 'RedWhiteCollar', name: 'Rouge, col blanc', preview: require('../../assets/icons/RedWhiteCollar/preview.png') },
  { id: 'SkyNavy', name: 'Bleu ciel, col marine', preview: require('../../assets/icons/SkyNavy/preview.png') },
  { id: 'AllWhiteGold', name: 'Tout blanc, filet or', preview: require('../../assets/icons/AllWhiteGold/preview.png') },
  { id: 'RedWhiteSleeves', name: 'Rouge, manches blanches', preview: require('../../assets/icons/RedWhiteSleeves/preview.png') },
  { id: 'RedWhiteSides', name: 'Rouge, flancs blancs', preview: require('../../assets/icons/RedWhiteSides/preview.png') },
  { id: 'YellowBlack', name: 'Jaune et noir', preview: require('../../assets/icons/YellowBlack/preview.png') },
  { id: 'GoldRed', name: 'Or et rouge', preview: require('../../assets/icons/GoldRed/preview.png') },
  { id: 'RedWhiteSplit', name: 'Coupé rouge et blanc', preview: require('../../assets/icons/RedWhiteSplit/preview.png') },
  { id: 'ForestGreen', name: 'Vert forêt', preview: require('../../assets/icons/ForestGreen/preview.png') },
  { id: 'WhiteChevron', name: 'Blanc, chevron bicolore', preview: require('../../assets/icons/WhiteChevron/preview.png') },
];
